### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
Thanks @martinRenou. Is the main purpose of this PR to update the compilers used?

Also, thanks for adding the `license_file` entry to meta.yaml. I think you can remove License.txt from the recipe folder here though (I think you only need to bundle the file itself [if it is missing from the source tarball](https://conda-forge.readthedocs.io/en/latest/meta.html#packaging-the-license-manually)).

**Comment by martinRenou** [comment]
> the main purpose of this PR to update the compilers used?

Yes :)

Ok, I will remove the license file then

**Comment by grlee77** [comment]
Thanks!

**Pull request merged**
